language: node_js
branches:
  only:
  - master
before_install:
- npm i -g npm@6
after_success:
- npm run build
- firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
env:
  global:
  - secure: GBfeaklpDi7nOqWLHnKmmTV7BMc+5I5R+bM6RH8kJXv68nZ+KrRYT5xPoOCoij/gEBDocdLCfU1EbJAlGnPjuZ21oSV/5UqlPd7VLPx0mF19C/dQwqwdGGszlexWeX+n85r27kEfgyYy8WLpUt5FKynW4/Hbn0+l6/4wg+O8DBJOfo54/UapvKnJYKk+57org42vLjDYs4UHY09T4KMrDlQbn09eDpMdzFInyyUklQPxlUT4inJWVp/Ze2cjG9Lh1bKhy9/rPzFx1unvcTqFMvYk4Njsen+8jpEqxdtutothYDibP7bwqTYaCdf++VDfZW9blt0rmpQRXmdjAbNQHma6sYg1vdMKn/gLrEHxJt+KvSTFFu8s9WaNO+1gR/oZ3FUalJVyqpXmFfoxf9QY5GIxb5arxwQS1vkbpuqZT4GlR7hOhCrjBYj8tS6MP+OtHWL60eEXcX934O+EtKfWzR14EmTJgY5yypA+7vobyFaSUnpVoIGEIfVbGOXGc/Gkod9NuzK2PDI43XfzfNhw4F5Xw8fmis/c/tAV+CNXWQhzdixQt0x1e14tCfN+6i+lAQw7SYEaCsx7Sm8gtpUWunivYGZaiEvrA4ru5kK9p5N7N3AO+0Vsm6Ufc98jomaPCdczpOY8AfKAE2lJ76SyzSuHsI2E3ax8FSl47QOJiPo=
