language: node_js

branches:
  only:
  - master

before_install:
- npm i -g npm@6

after_success:
- npm run deploy-ci

env:
  secure: o9OEpgH4VhabG6UDgU+CywzGryvR1svs4S+hiLBoClomzvBPXsBW+dJTs/1dm8hPdU0K00WPwp3caAsnRrRC5ch9TdE1LHGXVCyoZ66MW6OiYhs5wpozvvCz0/SNkMQoCvwAlJ0k6lY1P2S/kGvaAA6Mi8FptgLhjoSdqe+Qk58gwsOxYS2quILUkry7MRIOFktJKgC2E+mLDGbWs94dDrlPxd4LpkwkwZFLg9H7ttcateF7Pvj0O6r3Rcaa2caAB8nspvdzEOphNiKpXDqfQsZrLGtfbJwRxTxByliDqJ9iMZc7+wRP6PBgef5cJYgYkqxO9XZc7rl2V6ntfRxqemnTosj2ZHrBhaHqhLJ1XUEXAVnqgdYQ5Ikf/s15MPytiPVsUU1dCh646svM78an3Y38HrsjHTOlX+jY6cJlXjRLETAWFaIwO8fFOITwFDNGcKhUN3s4h54L7xVhXgpSbaoRmgk7nrU2HhsyxoBHVW247gJ1aNU2EYG+ovBamV/oEm/A/+hytgGcb0tNm3/ahBmMA5Vs7esorOTmgYyfERK9fui+mo6RzHXDUaDb3IKzNxqTcQb28T0fqfyrwXrn2lXFZqSDQKfBzQGe9bEOZvrFAVPvI9qcg1mnH+jUaVJX1jsb/VApUkCMJCAHT1tjaYjgixQVwPMgBXFlKD5RMQw=
