language: node_js
branches:
  only:
  - master
before_install:
- npm i -g npm@6
after_success:
- npm run build
- firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
env:
  global:
    secure: Ppk+jpou4FJUlxuOWzWwzYG8ivJ9HX6YC60Rs0xQyEpn4QocOkWp4Ti1Emp10958aC7DXKK9Gz9kZCCAlMjFqcY9AGig5eZLeYZ9mfPrOYNlUDIZF2J8EaEBRDSkWgPCp0yF81ixVLZqq9b5Q6pgTUHa7xyW8h2MvabUPIGaYtcWlG6RjzLMvsBt/q7MUl9ukxtrtFhQsTS+x5XVsGh8Z+FIyJGxqMsrOQeRpOu+DKi7rRFZgWpzxB+Dp4rTmM2hTnnnjeQcCkLKoc6RxfXxW2tcvVj7XDxu6s/Mbe+NBJ4s9DJUiiwETaJ1C1HCvYkYkEYc0Ld7EAk7lNvPSHsZCiyqKEpjtR/Vgb/A+9MHwe/qAjpM4hKpGqfOKAOON5Awmehx8OOB+y9XsUEvfIEubab178wAPmh5hPBy3f9zzzqfABW7QyU52lIfNee9WA2lLsLAa4CgZQ7HxJjXzITNztqAvNVO/HU3RzekL1Jbhrl8sOY6hJdOdeu/FRhyJpSGiDJTniZRxpdpv6OBdPN4PaHAPwEpAPCSNWSKOaIr8Fb3F68c1vFYvA/SsZLSCc6suZEGMszVwT+I5S3kwwcngpOfQ2fKCItG54SzWHo/OE0MjLK4pBvKbJcxIJdhK+V8PFhASl5/WAq4hhyhjiboGzPzt3URBQBsV5Fd6qmhXK0=
