language: node_js

deploy:
  provider: firebase
  token:
    secure: jWxZnEFF2q8/R1x9kvz4EDrYxLunbvYwgm1HSHXZxYi/+PVVoK0twrURm4EaOAB25LUKrdnot/S0Dungy+02A7sGXdO1DOaETP+D4DZ2eStYryoTaPVrGJwGrRlPLLiWktPST8dZfsUjb15N7ZwEuBsjT8b/D6ZusEIDxBznZm7YCbRaGZt+SHlsW+rYTBQtTVrXNnF7kwk/DT++krBRbt6+bmDQoz5z6/9CCTPrE8MZddSTWzFid59EdHQ30yV7nWvbQdfuhL+JqynJ4NdsT2Rpg9vnIk06SIjRpSqfH0TplbeWU4coAfgxHYuxvNupLWX46fZ4iQ7Mn1xkfDUoNPwRLY1kcECwlPSiH3jXesVl17Exkr5UI1dV4HH1j3b2FOyIp7Gaw+MAOXH5UKE3FoAW0p6ROlxvDFjhBWlmezzSj/3C/4Q2hExNqUrEG8Nu64UZ/sYQzY9CGoqL8okzBZy2918+MncBEMcIqIiNdigucXVSWQXjNjcym7K8VP7lTMFBv+AVRyP9LFzFSlgKDbs1WzbT1hpy6TOXTLY3AejXTzqsRyuaNdGN4IY5IejXsp/s6Kkt2j0vMaOCLGfCOFtv2rWkD7OIeRwB0mJ4Fem7XCPcXCPXfyBb7JG+TVUit8+lCn3GTQXKqknzHgKF9ESMgcSVnR6ffBawYdD6hLw=
